id = "united-gnome"
name = "United Gnome"
version = "0.3.1"
schema_version = 1
authors = ["Smyrnis Giannis <smyrnisgiannis@gmail.com>"]
description = "Color themes based on gnome"
repository = "https://github.com/Smyrnis/united-gnome-theme"
